# Generated by Django 4.1.4 on 2022-12-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='MEMID')),
                ('NAME', models.CharField(max_length=20, verbose_name='使用者名稱')),
                ('PHONE', models.CharField(max_length=10, verbose_name='手機')),
                ('PASSWORD', models.CharField(max_length=20, verbose_name='密碼')),
                ('NICKNAME', models.CharField(blank=True, max_length=20, verbose_name='暱稱')),
                ('POINT', models.IntegerField(blank=True, verbose_name='點數')),
                ('IDCARD', models.CharField(blank=True, max_length=10, verbose_name='身分證字號')),
            ],
        ),
    ]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='MEMID')),
                ('NAMES', models.CharField(max_length=20, verbose_name='使用者名稱')),
                ('QUESTIONS', models.CharField(max_length=500,verbose_name='問題回報'))
            ]

        )
    ]