# Generated by Django 4.1.4 on 2022-12-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userdata_id copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAMES', models.CharField(max_length=20, verbose_name='使用者名稱')),
                ('QUESTIONS', models.CharField(max_length=500, verbose_name='問題回報')),
            ],
        ),
    ]
