# Generated by Django 4.1.4 on 2022-12-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_qa'),
    ]

    operations = [
        migrations.CreateModel(
            name='memberlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMAGE', models.ImageField(upload_to='../static/images')),
                ('IMAGE_NUMBER', models.CharField(max_length=32, verbose_name='等級')),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='RANK',
            field=models.IntegerField(blank=True, default=1, verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='POINT',
            field=models.IntegerField(blank=True, default=0, verbose_name='點數'),
        ),
    ]
