# Generated by Django 4.1.4 on 2022-12-31 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_memberlevel_userdata_rank_alter_userdata_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='RANK',
        ),
    ]
