# Generated by Django 4.1.4 on 2023-01-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_qan'),
        ('myapp', '0006_qa_username_alter_qa_questions'),
    ]

    operations = [
    ]
