# Generated by Django 4.1.4 on 2023-01-01 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_merge_0003_qan_0006_qa_username_alter_qa_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('point', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('intro', models.CharField(max_length=600)),
                ('total', models.CharField(max_length=20)),
                ('date', models.DateField(verbose_name=datetime.datetime(2023, 1, 1, 22, 13, 22, 72336))),
            ],
        ),
        migrations.DeleteModel(
            name='QAN',
        ),
    ]
