# Generated by Django 4.1.4 on 2023-01-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_product_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='point',
            field=models.IntegerField(max_length=500),
        ),
    ]
