# Generated by Django 4.1.4 on 2023-01-03 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_product_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='userbuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('USERNAME', models.CharField(blank=True, max_length=20, verbose_name='使用者名稱')),
                ('PNAME', models.CharField(max_length=255, verbose_name='商品名稱')),
                ('REVENUE', models.CharField(max_length=255, verbose_name='收入')),
                ('EX', models.CharField(max_length=255, verbose_name='支出')),
                ('LEFT', models.CharField(max_length=255, verbose_name='剩餘點數')),
            ],
        ),
    ]
