# Generated by Django 4.1.4 on 2023-01-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_userbuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_image',
            field=models.ImageField(default='./static/imges/amphibian.png', upload_to='./static/images/'),
        ),
    ]
