# Generated by Django 4.1.4 on 2023-01-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_userdata_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_image',
            field=models.ImageField(default='./static/images/amphibian.png', upload_to='./static/images/'),
        ),
    ]
