# Generated by Django 4.1.4 on 2023-01-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_userdata_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_image', models.ImageField(upload_to='image/')),
                ('introduce', models.FileField(upload_to='introduce/')),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user_image',
        ),
    ]
