# Generated by Django 4.1.4 on 2023-01-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_user_remove_userdata_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_image',
            field=models.ImageField(default='./static/images/amphibian.png', upload_to='./static/images/'),
        ),
    ]
