# Generated by Django 4.1.4 on 2023-01-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_delete_user_userdata_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlevel',
            name='IMAGE_NUMBER',
            field=models.CharField(default='1', max_length=32, verbose_name='等級'),
        ),
    ]
